# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HabitualFrontEndRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HabitualFrontEndRN

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'HabitualFrontEndRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HabitualFrontEndRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HabitualFrontEndRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HabitualFrontEndRN-tvOS

  target 'HabitualFrontEndRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
